name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dep:
    uses: ./.github/workflows/multi-nothing.yml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  even-no-dep:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello
    needs:
      - dep
